import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

import AuthProvider from '@/components/AuthProvider'
import NavBar from '@/components/NavBar'
import { ReactQueryProvider } from '@/components/ReactQueryProvider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Reddit: the front page of the internet',
  description: 'Generated by create next app',
}

const Providers = ({ children }: { children: React.ReactNode }) => {
  return (
    <ReactQueryProvider>
      <AuthProvider>{children}</AuthProvider>
    </ReactQueryProvider>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex min-h-screen flex-col justify-between">
            <NavBar />
            <main className="max-w-full overflow-x-clip px-4 pt-12 text-sm text-reddit-white md:px-6">{children}</main>
          </div>
        </Providers>
        <ToastContainer theme="dark" autoClose={2000} />
      </body>
    </html>
  )
}
