import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import AuthProvider from '@/components/AuthProvider'
import { SessionProvider } from '@/components/SessionContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Reddit Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SessionProvider>
            <div className='flex flex-col justify-between min-h-screen'>
              <NavBar />
              <main className='px-4 py-12 text-sm text-reddit-white'> {/* py-12 is for the height of the fixed navbar. */}
                {children}
              </main>
            </div>
          </SessionProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
